name: telegram-downloader-bot

services:
  - name: bot-worker
    # Use 'worker' since this is a long-running bot, not a web server
    type: worker
    instanceType: nano
    
    build:
      buildpack:
        # This tells Koyeb to install the ffmpeg system package
        packages:
          - ffmpeg
    
    run:
      # This command runs your bot
      command: python telegram_bot.py

    env:
      - key: BOT_TOKEN
        scope: secret
        # This links to the Secret you will create in the Koyeb dashboard

        valueFrom: my-bot-token





